name: Gradle jvmJar
on: 
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      fail-fast: false  
      matrix:
        include:
          - arch: aarch64
            os: macos-latest
            target: macos
            lipo-arch: arm64
          - arch: amd64
            os: macos-latest
            target: macos
            lipo-arch: x86_64
          - arch: amd64
            os: windows-latest
            target: windows
          - arch: amd64
            os: ubuntu-latest
            target: linux
    name: ${{ matrix.target }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle jvmJar
      run: ./gradlew jvmJar

    - name: 'Upload jvmJar artifact'
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.target }}-${{ matrix.arch }}
        path: build/libs/
