name: Gradle Build
on: 
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        dependency-graph: generate-and-submit
    
    - name: Execute Gradle build
      run: ./gradlew build
